# ===============================
#
#       Build - Makefile
#   Written For Windows Systems
#
# ===============================

CC = gcc

# ----- Build Source Code ----- #



# ----- Clean Build Files ----- #